# Generated by Django 3.0.7 on 2020-06-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='bank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
