# Generated by Django 3.0.7 on 2020-06-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200614_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_name',
        ),
    ]
