# Generated by Django 3.0.7 on 2020-06-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_profile_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sex',
            new_name='account_name',
        ),
    ]
