# Generated by Django 3.0.7 on 2020-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200620_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='to_receive',
            new_name='total',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
