# Generated by Django 3.0.7 on 2020-06-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200620_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
