# Generated by Django 3.0.7 on 2020-06-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_plan_is_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='user',
            new_name='to_pay',
        ),
        migrations.AddField(
            model_name='receiver',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiver',
            name='to_collect',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Plan'),
        ),
    ]
