# Generated by Django 3.0.7 on 2020-06-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200621_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='to_collect',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
