# Generated by Django 3.0.7 on 2020-06-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200622_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='to_pay',
            new_name='person_to_pay',
        ),
    ]
