# Generated by Django 3.0.7 on 2020-06-22 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20200622_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='the_receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
